AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"


Parameters:
  VpcCIDR:
    Type: String
  vpcname:
    Type: String
  

Resources:

  NestedVPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/project-data-20/rds.yml
      Parameters:
        VpcCIDR: !Ref VpcCIDR
        vpcname: !Ref vpcname
        
